In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\AWS_Supply_Chain_Review\SQL_Assessment_Team\dataset\aws_supply_chain_orders_raw.csv", encoding="utf-8")

In [3]:
df.head()

,order_id,warehouse,region,product,order_qty,order_date,delivery_date,delivery_time_days,status
0,ORD-1000,WH-C,West,Router,42,2026-02-16 06:22:56.185879,2026-03-24 06:22:56.186200,4.0,Pending
1,ORD-1001,WH-A,West,Laptop,30,2026-02-25 06:22:56.185905,2026-03-15 06:22:56.186205,12.0,Pending
2,ORD-1002,WH-C,South,Switch,19,2026-03-13 06:22:56.185910,2026-03-13 06:22:56.186207,13.0,Pending
3,ORD-1003,WH-C,North,Server,17,2026-02-14 06:22:56.185913,2026-03-01 06:22:56.186209,9.0,Pending
4,ORD-1004,WH-A,East,Laptop,19,2026-02-18 06:22:56.185916,2026-03-11 06:22:56.186211,3.0,Delivered

Task 2: Data Cleaning

Perform:
Missing Value Handling

Replace missing numerical values

In [4]:
df['delivery_time_days']=df['delivery_time_days'].fillna(df['delivery_time_days'].mean())

Replace missing categorical values

In [5]:
df['region']=df['region'].fillna('East')

Duplicate Removal

Remove duplicate records.

In [6]:
df=df.drop_duplicates()

Data Type Standardization

Examples:
Date Columns → DATE/TIMESTAMP
Quantity → INTEGER
Revenue → DECIMAL

In [7]:
df.dtypes

order_id                  str
warehouse                 str
region                    str
product                   str
order_qty               int64
order_date                str
delivery_date             str
delivery_time_days    float64
status                    str
dtype: object

In [8]:
df['delivery_time_days']=df['delivery_time_days'].astype(int)
df['delivery_date']=pd.to_datetime(df['delivery_date'])
df['order_date']=pd.to_datetime(df['order_date'])

Data Validation

Identify:
Negative quantities

In [9]:
negative_quantities=df[df['order_qty']<0]
negative_quantities

Empty DataFrame
Columns: [order_id, warehouse, region, product, order_qty, order_date, delivery_date, delivery_time_days, status]
Index: []

Invalid dates

In [10]:
invalid__order_date=df['order_date'].isna()
invalid_delivery_date=df['delivery_date'].isna()
print(invalid__order_date.sum())
print(invalid_delivery_date.sum())

0
0

Incorrect category mappings

In [11]:
valid_region=['East','West','North','South']
invalid_region=df[df['region'].isin(valid_region)]
invalid_region


valid_status=['Delivered','Delayed','Pending']
invalid_status=df[df['status'].isin(valid_status)]
invalid_status

,order_id,warehouse,region,product,order_qty,order_date,delivery_date,delivery_time_days,status
0,ORD-1000,WH-C,West,Router,42,2026-02-16 06:22:56.185879,2026-03-24 06:22:56.186200,4,Pending
1,ORD-1001,WH-A,West,Laptop,30,2026-02-25 06:22:56.185905,2026-03-15 06:22:56.186205,12,Pending
2,ORD-1002,WH-C,South,Switch,19,2026-03-13 06:22:56.185910,2026-03-13 06:22:56.186207,13,Pending
3,ORD-1003,WH-C,North,Server,17,2026-02-14 06:22:56.185913,2026-03-01 06:22:56.186209,9,Pending
4,ORD-1004,WH-A,East,Laptop,19,2026-02-18 06:22:56.185916,2026-03-11 06:22:56.186211,3,Delivered
...,...,...,...,...,...,...,...,...,...
145,ORD-1145,WH-C,North,Storage,25,2026-02-25 06:22:56.186170,2026-03-10 06:22:56.186457,6,Pending
146,ORD-1146,WH-C,North,Server,22,2026-01-31 06:22:56.186172,2026-02-23 06:22:56.186458,12,Delivered
147,ORD-1147,WH-C,East,Switch,13,2026-02-20 06:22:56.186174,2026-03-08 06:22:56.186460,8,Pending
148,ORD-1148,WH-A,West,Server,19,2026-02-18 06:22:56.186176,2026-03-07 06:22:56.186462,12,Delayed
149,ORD-1149,WH-A,East,Storage,49,2026-02-15 06:22:56.186196,2026-02-26 06:22:56.186464,5,Delayed

Generate csv file for the cleaned data

In [12]:
df.to_csv(
    "cleaned_data\\aws_supply_chain_orders_clean.csv",
    index=False
)